
  Skip to content
    Pull requests
    Issues
    Marketplace
    Explore
    @BouttesINSEE
    ddecrulle /
    Knowledge-Back-Office
    Public
    forked from bwerquin/Knowledge-Back-Office
    
    Code
    Pull requests
    Actions
    Projects
    Wiki
    Security

    Insights
    
    Knowledge-Back-Office/.github/workflows/build.yml
    @ddecrulle
    ddecrulle Update build.yml
    Latest commit 40b5401 on 14 Feb
    History
    2 contributors
    @bwerquin
    @ddecrulle
    67 lines (65 sloc) 1.92 KB
  name: Build

  on:
    push:
      branches:
        - 'main'
      tags:
        - '*'

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Build with Maven
          run: mvn install --file pom.xml
        - name: Upload war
          uses: actions/upload-artifact@v2
          with:
            name: jar
            path: target/*.jar
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout current branch
          uses: actions/checkout@v2
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - name: Release snapshot
          id: release-snapshot
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{steps.version.outputs.prop}}
            release_name: Release ${{steps.version.outputs.prop}}
            draft: false
            prerelease: false
    docker:
      needs: build
      runs-on: ubuntu-latest
      environment: ci
      steps:
        - uses: actions/checkout@v2
        - name: Download build
          id: download
          uses: actions/download-artifact@v2
          with:
            name: jar
            path: target/
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: ddecrulle/knowledge-back-office
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            tags: ${{steps.version.outputs.prop}}

      © 2022 GitHub, Inc.
      
      Terms
      Privacy
      Security
      Status
      Docs
      Contact GitHub
      Pricing
      API
      Training
      Blog
      About

    You signed in with another tab or window. Reload to refresh your session.
    Loading complete